learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#Template Tagging/ base urls for relative links in app

app_name = 'basic_app'

urlpatterns=[
    url(r'^relative/$',views.relative,name="relative"),
    url(r'^other/$',views.other,name="other"),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    path('admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
            <a class="nav-item nav-link" href="{% url 'basic_app:other' %}">Other</a>
            <a class="nav-item nav-link disabled" href="{% url 'basic_app:relative' %}">Relative URL Template</a>
          </div>
        </div>
    </nav>
    <div class="container">

        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend! -->

        {% endblock %}
    </div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>Welcome to Index</h1>
    <!-- <h2>This is index.html page showing!</h2> -->
    <!-- This below is an example of custom filter -->
    <!-- <h1>{{ text|upper }}</h1> --> 
    <!-- <h1>{{ text|cut:'hello' }}</h1> -->
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:"99" }}</h1>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>Welcome to Other</h1>
    <h2>This is an example of template inheritance!</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>
<body>
    <h1>Welcome To Relative URL Template</h1>
    <a href="{% url 'basic_app:other' %}">The Other Page</a><br />
    <a href="{% url 'admin:index' %}">Go to Admin</a><br />
    <a href="{% url 'index' %}">Back to Home/Index</a>
</body>
</html>